# Use official node image as the base image

# Set the working directory

# Add the source code to app

# Install all the dependencies

# Generate the build of the application



# Stage 2: Serve app with nginx server

# Use official nginx image as the base image

# Copy the build output to replace the default nginx contents.

# Expose port 80
